version: 2.1

workflows:
  Run tests:
    jobs:
      - Install dependencies
      - Build:
          requires:
            - Install dependencies

aliases:
  - &restore_pnpm_cache
    restore_cache:
      name: Restore pnpm cache
      keys:
        - pnpm-{{ checksum "pnpm-lock.yaml" }}
        - pnpm-

  - &install_dependencies
    run:
      name: Install dependencies using pnpm
      command: |
        corepack enable
        pnpm config set store-dir ~/.pnpm-store
        pnpm store path
        pnpm install --ignore-scripts

jobs:
  Install dependencies:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - *restore_pnpm_cache
      - *install_dependencies
      - save_cache:
          name: Save pnpm cache
          key: pnpm-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store

  Build:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - *restore_pnpm_cache
      - *install_dependencies
      - run:
          name: Build monorepo packages
          environment:
            TURBO_UI: 'false'
          command: pnpm build

