version: 2.1

workflows:
  test:
    jobs:
      - Install dependencies
      - Build:
          requires:
            - Install dependencies

jobs:
  Install dependencies:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm cache
          keys:
            - pnpm-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Enable Corepack
          command: |
            corepack enable
            pnpm config set store-dir ~/.pnpm-store
      - run:
          name: Install dependencies with pnpm
          command: pnpm install
      - save_cache:
          name: Save pnpm cache
          key: pnpm-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store

  Build:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - run:
          name: Build monorepo packages
          command: pnpm build
