version: 2.1

workflows:
  test:
    jobs:
      - Install dependencies
      - Build:
          requires:
            - Install dependencies

alias:
  - &restore_pnpm_cache
    restore_cache:
      name: Restore pnpm cache
      keys:
        - pnpm-{{ checksum "pnpm-lock.yaml" }}

jobs:
  Install dependencies:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - *restore_pnpm_cache
      - run:
          name: Enable Corepack
          command: |
            corepack enable
            pnpm config set store-dir ~/.pnpm-store
      - run:
          name: Install dependencies with pnpm
          command: pnpm install --ignore-scripts
      - save_cache:
          name: Save pnpm cache
          key: pnpm-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store

  Build:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - *restore_pnpm_cache
      - run:
          name: Build monorepo packages
          command: pnpm build
