version: 2.1

workflows:
  Run E2E:
    jobs:
      - Install dependencies
      - Build:
          requires:
            - Install dependencies

alias:
  - &restore_pnpm_cache
    restore_cache:
      name: Restore pnpm cache
      keys:
        - pnpm-{{ checksum "pnpm-lock.yaml" }}
        - pnpm-

jobs:
  Install dependencies:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - *restore_pnpm_cache
      - run:
          name: Install dependencies with pnpm
          command: |
            pnpm install --ignore-scripts
            pnpm config set store-dir .pnpm-store
            pwd
            ls -la
      - save_cache:
          name: Save pnpm cache
          key: pnpm-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store

  Build:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - *restore_pnpm_cache
      - run:
          name: Build monorepo packages
          environment:
            TURBO_UI: 'false'
          command: echo 'Running build...'

