version: 2.1

workflows:
  Run tests:
    jobs:
      - Install dependencies
      - Build:
          requires:
            - Install dependencies
      - Run Playwright tests:
          name: Run pos-web tests
          project: pos-web
          requires:
            - Build

aliases:
  - &restore_pnpm_cache
    restore_cache:
      name: Restore pnpm cache
      keys:
        - pnpm-{{ checksum "pnpm-lock.yaml" }}
        - pnpm-

  - &install_dependencies
    run:
      name: Install dependencies using pnpm
      command: |
        sudo npm install -g corepack@latest
        sudo corepack enable
        pnpm config set store-dir ~/.pnpm-store
        pnpm install --ignore-scripts

  - &build
    run:
      name: Build monorepo packages
      environment:
        TURBO_UI: 'false'
      command: pnpm build

jobs:
  Install dependencies:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - *restore_pnpm_cache
      - *install_dependencies
      - save_cache:
          name: Save pnpm cache
          key: pnpm-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store

  Build:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - *restore_pnpm_cache
      - *install_dependencies
      - *build

  Run Playwright tests:
    docker:
      - image: cimg/openjdk:23.0-node
    resource_class: small
    parallelism: 3
    parameters:
      project:
        type: string
    steps:
      - checkout
      - *restore_pnpm_cache
      - *install_dependencies
      - *build
      - run:
          name: Install Playwright browsers
          command: pnpm playwright:install-browsers
      - run:
          name: 'Run tests for project: << parameters.project >>'
          command: |
            cd e2e/<< parameters.project >>
            pnpm test --shard=$((${CIRCLE_NODE_INDEX}+1))/${CIRCLE_NODE_TOTAL}
      - store_test_results:
          path: e2e/<< parameters.project >>/playwright-report/results.xml
