export type Browser = 'chrome' | 'edge';

export type HTTPMethod = 'GET' | 'POST' | 'PUT' | 'DELETE';

export interface TestOptions {
	timeout?: number;
}

/**
 * Page identifiers
 */
export enum PageId {
	HOME = 'HOME',
	LOGIN = 'LOGIN',
	TICKET_VIEW = 'TICKET_VIEW',
	WAITING_LIST = 'WAITING_LIST',
	GIFT_CARD_BALANCE = 'GIFT_CARD_BALANCE',
	LOYALTY_BALANCE = 'LOYALTY_BALANCE',
	CLOSED_TICKETS = 'CLOSED_TICKETS',
	APPOINTMENT = 'APPOINTMENT',
	TICKET_ADJUSTMENT = 'TICKET_ADJUSTMENT',
	PAYROLL = 'PAYROLL',
	TURN_DETAILS = 'TURN_DETAILS',
	EMPLOYEES = 'EMPLOYEES',
	CATEGORIES = 'CATEGORIES',
	PRODUCTS = 'PRODUCTS',
	TAX = 'TAX',
	DISCOUNT = 'DISCOUNT',
	DEPARTMENT = 'DEPARTMENT',
	VOID_REASONS = 'VOID_REASONS',
	APPOINTMENT_COLOR = 'APPOINTMENT_COLOR',
	APPOINTMENT_TYPES = 'APPOINTMENT_TYPES',
	CUSTOMERS = 'CUSTOMERS',
	CLOSE_OUT = 'CLOSE_OUT',
}

export enum UserRole {
	ADMIN = 'ADMIN',
	// more roles go here
}
