export type Browser = 'chrome' | 'edge';

export type HTTPMethod = 'GET' | 'POST' | 'PUT' | 'DELETE';

export interface TestOptions {
	timeout?: number;
}

/**
 * Page identifiers
 */
export enum PageId {
	HOME = 'HOME',
	LOGIN = 'LOGIN',
	TICKET_VIEW = 'TICKET_VIEW',
	WAITING_LIST = 'WAITING_LIST',
	GIFT_CARD_BALANCE = 'GIFT_CARD_BALANCE',
	LOYALTY_BALANCE = 'LOYALTY_BALANCE',
	CLOSED_TICKETS = 'CLOSED_TICKETS',
	APPOINTMENT = 'APPOINTMENT',
	TICKET_ADJUSTMENT = 'TICKET_ADJUSTMENT',
	PAYROLL = 'PAYROLL',
	TURN_DETAILS = 'TURN_DETAILS',
	EMPLOYEES = 'EMPLOYEES',
	EMPLOYEES_CREATE = 'EMPLOYEES_CREATE',
	CATEGORIES = 'CATEGORIES',
	CATEGORIES_CREATE = 'CATEGORIES_CREATE',
	PRODUCTS = 'PRODUCTS',
	TAX = 'TAX',
	DISCOUNT = 'DISCOUNT',
	DISCOUNT_CREATE = 'DISCOUNT_CREATE',
	DEPARTMENT = 'DEPARTMENT',
	VOID_REASONS = 'VOID_REASONS',
	APPOINTMENT_COLOR = 'APPOINTMENT_COLOR',
	APPOINTMENT_TYPES = 'APPOINTMENT_TYPES',
	CUSTOMERS = 'CUSTOMERS',
	CLOSE_OUT = 'CLOSE_OUT',
	TICKET_PAYMENTS = 'TICKET_PAYMENTS',
	WAIT_LOG = 'WAIT_LOG',
	APPOINTMENT_LOG = 'APPOINTMENT_LOG',
	ACTIVITY_LOG = 'ACTIVITY_LOG',
	SMS_LOG = 'SMS_LOG',
	RUN_LOG = 'RUN_LOG',
	CONNECTION_LOG = 'CONNECTION_LOG',
	QUICK_PAYROLL = 'QUICK_PAYROLL',
	CASH_IN_OUT = 'CASH_IN_OUT',
	MANAGER_TIMESHEET = 'MANAGER_TIMESHEET',
	ONLINE_GIFT_CARD_INVENTORY = 'ONLINE_GIFT_CARD_INVENTORY',
	PAID_ONLINE_GIFT_CARD = 'PAID_ONLINE_GIFT_CARD',
}

export enum UserRole {
	ADMIN = 'ADMIN',
	// more roles go here
}
