name: Codacy Analysis

on:
  push:
    branches: [ main ]

  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    branches: [ main ]

permissions: read-all

jobs:
  codacy_analysis:
    name: Analyze

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          upload: true
