name: Lint

on:
  push:
    branches: [ $default-branch ]
  pull_request_target:
    branches: [ $default-branch ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.tool-versions'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          npm install -g corepack@latest
          corepack enable
          pnpm install --ignore-scripts

      - name: Run lint
        run: pnpm lint
